-- =============================================================================
-- 20260314000003_account_role_mapping.sql
-- account + role_master + role_mapping (roles via mapping, not stored on account)
-- =============================================================================

create table if not exists public.role_master (
  id bigint generated by default as identity primary key,
  role_name text not null unique,
  created_at timestamptz not null default now()
);

insert into public.role_master (id, role_name)
overriding system value
values
  (1, 'Author'), 
  (2, 'Editor'),
  (3, 'Administrator') 
on conflict (id) do nothing;

-- Keep identity sequence in sync after explicit ids
select setval(
  pg_get_serial_sequence('public.role_master', 'id'),
  greatest((select coalesce(max(id), 1) from public.role_master), 1)
);

create table if not exists public.account (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  full_name text not null default '',
  email text not null,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint account_email_unique unique (email)
);

create index if not exists account_auth_user_id_idx on public.account (auth_user_id);

create table if not exists public.role_mapping (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.account (id) on delete cascade,
  role_id bigint not null references public.role_master (id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint role_mapping_account_role_unique unique (account_id, role_id)
);

create index if not exists role_mapping_account_id_idx on public.role_mapping (account_id);
create index if not exists role_mapping_role_id_idx on public.role_mapping (role_id);

alter table public.role_master enable row level security;
alter table public.account enable row level security;
alter table public.role_mapping enable row level security;

drop policy if exists role_master_read on public.role_master;
create policy role_master_read
  on public.role_master for select
  to authenticated, anon
  using (true);

drop policy if exists account_self_read on public.account;
create policy account_self_read
  on public.account for select
  to authenticated
  using (auth_user_id = auth.uid());

drop policy if exists account_self_update_password_flag on public.account;
create policy account_self_update_password_flag
  on public.account for update
  to authenticated
  using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

drop policy if exists account_admin_all on public.account;
create policy account_admin_all
  on public.account for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.is_active = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.is_active = true
    )
  );

drop policy if exists role_mapping_self_read on public.role_mapping;
create policy role_mapping_self_read
  on public.role_mapping for select
  to authenticated
  using (
    exists (
      select 1 from public.account a
      where a.id = role_mapping.account_id and a.auth_user_id = auth.uid()
    )
  );

drop policy if exists role_mapping_admin_all on public.role_mapping;
create policy role_mapping_admin_all
  on public.role_mapping for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.is_active = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin' and p.is_active = true
    )
  );
